version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack edge port for AWS services
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./.localstack:/var/lib/localstack"

  setup-s3-notifications:
    build:
      context: .
      dockerfile: Setup_S3_Notifications_Dockerfile
    container_name: setup-s3-notifications
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
    restart: "no"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9001:9001" # MinIO Console (Web UI)
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=http://localstack:4566
    command: server /data --console-address ":9001"
    depends_on:
      - localstack
